### PR TITLE
Fixed tls transport reuse bug that caused the all file descriptors to…

### PR DESCRIPTION
**Pull request by briantoth**
… be consumed.

### CODE REVIEW

**Comment by briantoth** [comment]
https://groups.google.com/forum/#!topic/golang-nuts/c0AnWXjzNIA was invaluable in debugging this

**Comment by dtolnay** [comment]
Make sure the gosexy PR is fixed too.

**Comment by briantoth** [comment]
@gdearment -do you mind updating your PR?  looks like i can't do it myself

**Comment by gdearment** [comment]
Yep, I'll update tomorrow.

Sent from my iPhone

On Sep 22, 2015, at 7:55 PM, briantoth <notifications@github.com<mailto:notifications@github.com>> wrote:

@gdearmenthttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_gdearment&d=BQMCaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=HrIkVYk7Wk9uCvanaPnFwdkIi7OSu6nydQ89HxcwIb0&m=VfgGFj1akcdKEBch-iuaXX55tBLFAUyYvm9bYW0mluY&s=0n2Rtsd3XCV8JyNcbOaF4IQuWNwvIVOXsixcbN1Vfak&e= -do you mind updating your PR? looks like i can't do it myself

**Pull request merged**
